@startuml attestation
!pragma layout smetana
!option handwritten true
'suppress component icon
skinparam ComponentStyle rectangle
skinparam backgroundColor transparent

[Hardware provider] as hp
[Cloud provider] as cp
[Attestation provider] as ap
[Customer software] as cs

note top of ap: attests integrity measurements
note bottom of hp: defines integrity measurements
note bottom of cp: allows integrity measurements

ap <-[#red,dashed]down-> hp : <color #red><size:20> <&circle-x></size></color>
ap <-[#red,dashed]down-> cp : <color #red><size:20> <&circle-x></size></color>
hp <-[#red,dashed]right-> cp : <color #red><size:20> <&circle-x></size></color>

ap -[#green]down-> cs : <color #green><size:20> <&circle-check></size></color>
hp -[#green]up-> cs : <color #green><size:20> <&circle-check></size></color>
cp -[#green]up-> cs : <color #green><size:20> <&circle-check></size></color>

legend
<color #green><size:20><&circle-check></size></color>: permit execution
====
<color #red><size:20><&circle-x></size></color>: segregation of duties(SoD) across entities
end legend

@enduml
