title: Attestation {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

Attester: Attester 
Verifier: Verifier
RVP: Reference Value Provider

RVP -> Attester: provides hardware
Verifier -> RVP : asks for reference values
Attester <-> Verifier : req/resp verification