@startuml coco_deployment
!option handwritten true
skinparam backgroundColor transparent
actor admin as "admin"

node K8S_Worker [
K8S worker
----
Libvirt
]

frame VM_TEE {

    frame kata_containers_agent {
        [deployment]

    }
    
    [coco_att_agent] as "Confidential Containers Attestation Agent (CCAA)"
    [coco_CDH] as "Confidential Data Hub (CDH)"
    
    note bottom: CDH uses token provided via CCAA
}


frame trustee as "Trustee" {   
}

admin -> K8S_Worker : Deployment
K8S_Worker -> VM_TEE : Libvirt boots (config via kernel params)
K8S_Worker -> kata_containers_agent : k8s communication
kata_containers_agent -> deployment : sandboxes
coco_CDH --> deployment : transparently provides resources

coco_att_agent <--> trustee : verification / token grant
coco_CDH <--> trustee : pulls resources

@enduml