@startuml
!option handwritten true
skinparam backgroundColor transparent
skinparam rectangle {
  BorderColor #333333
  FontColor #FFFFFF
  FontSize 14
}

title Trusted compute base

' Top level (narrowest)
rectangle "Confidentiality" as confidential #4CAF50 

' Application
rectangle "Application \n• " as application #2196F3 

' Configuration
rectangle "Secrets Handling \n• " as configuration #2196F3 

' RATS
rectangle "Remote Attestation\n• " as rats #9C27B0 

' Root
rectangle "Hardware Root of Trust & Measurements\n• " as hardware #FF9800 


' Ordering
confidential --> application : "builds on"
application --> configuration : "builds on"
configuration --> rats : "builds on"
rats --> hardware : "builds on"


@enduml